[build]
  publish = "_output"
  command = "make netlify"

[[redirects]]
  from = "/"
  to = "/business-admin"
  status = 302

[[redirects]]
  from = "/business-admin/quickstart/paymentmethod.html"
  to = "/business-admin/billing/payment-method.html"
  status = 302

[[redirects]]
  from = "/business-admin/account/contact.html"
  to = "/business-admin/billing/invoice-contact.html"
  status = 302

[[redirects]]
  from = "/business-admin/aes/aessetup.html"
  to = "/business-admin/aes/setup.html"
  status = 302

[[redirects]]
  from = "/business-admin/aes/aesproduct.html"
  to = "/business-admin/aes/setup.html"
  status = 302
  
  [[redirects]]
  from = "/business-admin/account/cancel.html"
  to = "/business-admin/quickstart/cancel.html"
  status = 302

[[redirects]]
  from = "/business-admin/quickstart/paymentmethod"
  to = "/business-admin/billing/payment-method.html"
  status = 302

[[redirects]]
  from = "/business-admin/account/contact"
  to = "/business-admin/billing/invoice-contact.html"
  status = 302

[[redirects]]
  from = "/business-admin/aes/aessetup"
  to = "/business-admin/aes/setup.html"
  status = 302

[[redirects]]
  from = "/business-admin/aes/aesproduct"
  to = "/business-admin/aes/setup.html"
  status = 302
  
    [[redirects]]
  from = "/business-admin/account/cancel"
  to = "/business-admin/quickstart/cancel.html"
  status = 302
  
